---
image: "patchshorts/build202004:v1"

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - export PACKAGES=`cat packages.list | xargs echo`
  - echo "Updating repos and installing packages listed in packages.list..."
  - apt-get update > /dev/null 2>&1
  - apt-get install $PACKAGES -y > /dev/null 2>&1
  - echo "Done"

stages:
  - build
  - test
  - run

build:
  stage: build
  script:
    - python3 ./deb-changectl/deb-changectl.py -R -t $CI_COMMIT_TAG -m $CI_COMMIT_MESSAGE;python3 ./deb-changectl/deb-changectl.py -R -G debian/changelog -R -t $CI_COMMIT_TAG -m $CI_COMMIT_MESSAGE
    - find ./ -name changelog -type f -exec cat {} \;
    - echo "Building..."
    - /usr/bin/dpkg-buildpackage -kdevops@puppet-control.home.local
    - echo "Done. Copying to upstream repos."
    - find ../ -name "deb-changectl_${CI_COMMIT_TAG}*" -exec sshpass -p devops scp -o StrictHostKeyChecking=no {} devops@192.168.4.59:/srv/deb/debian/incoming/ \;
    - echo "Done."
  only:
    - tags

build-snapshots:
  stage: build
  script:
    - python3 ./deb-changectl/deb-changectl.py -c $CI_COMMIT_SHORT_SHA -t $CI_COMMIT_SHORT_SHA -m $CI_COMMIT_MESSAGE;python3 ./deb-changectl/deb-changectl.py -G debian/changelog -c $CI_COMMIT_SHORT_SHA -t $CI_COMMIT_SHORT_SHA -m $CI_COMMIT_MESSAGE
    - find ./ -name changelog -type f -exec cat {} \;
    - echo "Building..."
    - /usr/bin/dpkg-buildpackage -kdevops@puppet-control.home.local
    - find ../ -name "deb-changectl_${CI_COMMIT_SHORT_SHA}*" -exec sshpass -p devops scp -o StrictHostKeyChecking=no {} devops@192.168.4.59:/srv/deb/debian/incoming/ \;
    - echo "Done."
  only:
    - master
