---
image: "ubuntu:latest"

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - export PACKAGES=`cat packages.list | xargs echo`
  - echo "Updating repos and installing packages listed in packages.list..."
  - apt-get update > /dev/null 2>&1
  - apt-get install $PACKAGES -y > /dev/null 2>&1
  - echo "Done"

stages:
  - build
  - test
  - run

build:
  stage: build
  script:
    - ./deb-changectl -b "${CI_JOB_ID}" -R -t "${CI_COMMIT_TAG}" -m "${CI_COMMIT_MESSAGE}" debian/changelog
    - find ./ -name changelog -type f -exec cat {} \;
    - echo "Building..."
    - /usr/bin/dpkg-buildpackage -kpatchshorts@gmail.com
    - echo "Uploading packages to repository"
    - dput ppa:patchshorts/gutils ../deb-changectl_*_source.changes
    - echo "Done."
  only:
    - tags

build-snapshots:
  stage: build
  script:
    - ./deb-changectl -b "${CI_JOB_ID}" -c "${CI_COMMIT_SHORT_SHA}" -t "${CI_COMMIT_SHORT_SHA}" -m "${CI_COMMIT_MESSAGE}" debian/changelog
    - find ./ -name changelog -type f -exec cat {} \;
    - echo "Building..."
    - /usr/bin/dpkg-buildpackage -kpatchshorts@gmail.com
    - dput ppa:patchshorts/gutils ../deb-changectl_*_source.changes
    - echo "Done."
  only:
    - master
